os:
  - osx

language: c

install:
  - brew update && brew install criterion readline lcov gcovr

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3

jobs:
  include:
    - stage: build
      script:
        - make debug
   - stage: Unit tests
     script:
       - make test
   - stage: Lexer tests
      after_script:
         - make coverage
      - bash <(curl -s https://codecov.io/bash)      - make coverage
