name: CI

on:
  push:
    branches:
      - 🔧Expander
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update && brew install criterion readline lcov

      - name: Build project
        run: make

      - name: Run tests and generate coverage report
        run: make test_re && gcovr --xml-pretty --output=coverage.xml
      - name: Coveralls
        uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          path: coverage.xml
