name: unit
on:
  push:
    branches:
      - main
      - 🔧Expander
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libreadline-dev lcov libcriterion-dev
          sudo pip install cpp-coveralls
      - name: Build project
        run: make
      - name: Run tests
        run: make test_re
      - name: Make Coverage report
        run: |
          make gcov
          coveralls --exclude lib --exclude tests --gcov-options '\-lp'
