name: unit
on:
  push:
    branches:
      - main
      - 🔧Expander
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          if [ "$MATRIX_OS" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install libreadline-dev lcov libcriterion-dev
          elif [ "$MATRIX_OS" = "macos-latest" ]; then
            brew update && brew install criterion readline lcov gcovr
          fi
      - name: locate criterion
        run: whereis criterion
      - name: Build project
        run: make
      - name: Run tests
        run: make test
      - name: Make Coverage report
        run: make coverage
