name: unit
on:
  push:
    branches:
      - main
      - 🔧Expander
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libreadline-dev lcov libcriterion-dev
          sudo pip install cpp-coveralls
      - name: Build project
        run: make
      - name: Run tests
        run: make test_re
      - name: Run tests
        run: make coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage.info
