name: unit
on:
  push:
    branches:
      - main
      - 🔧Expander
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libreadline-dev lcov libcriterion-dev
      - name: locate criterion
        run: whereis criterion
      - name: Build project
        run: make
      - name: Run tests
        run: make test
      - name: Make Coverage report
        run: make coverage
